name: Lint
on:
  push:
env:
  PIPENV_VENV_IN_PROJECT: enabled
jobs:
  make-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pipenv
      run: python -m pip install --upgrade pipenv==2021.5.29 wheel

    - name: Install dependencies
      run: pipenv install pylint

    - name: Check code
      run: pipenv run pylint --rcfile=.pylintrc **/*.py
