name: Lint
on:
  push:
env:
  PIPENV_VENV_IN_PROJECT: enabled
jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pipenv
      run: python -m pip install --upgrade pipenv==2021.5.29 wheel

    - name: Restore pipenv cache
      id: cache-pipenv
      uses: actions/cache@v2
      with:
        path: ./.venv
        key: test-${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pipenv install pylint

    - name: Check code
      run: pipenv run pylint --rcfile=.pylintrc **/*.py
